name: tasknow
description: "An academic project to keep interaction between patients and doctors."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6


  # JEDIDI add dependencies

  # Google_font Fonts
  google_fonts: ^4.0.4


  ###### Background Remover Begin ######
  image_picker: ^1.0.7
  # Compare imagae before after
  before_after_image_slider_nullsafty: ^1.0.1
  #screenshot: ^1.3.0
  #permission_handler: ^10.2.0
  ## Save files and Cache local
  #path_provider: ^2.0.15
  ## Save to gallery from cache
  #gallery_saver: ^2.3.2

  #########################################################################"Ana Fasakht"
  #########################################################################""
  #########################################################################""
  #########################################################################""
  # Save image directlly V2 from Ui8
  gallery_saver: ^2.3.2
  # dio http library for FormData for web response file in bytes not string
  dio: ^5.4.1
  # Alternative dart io but on browser also
  universal_io: ^2.2.2
  # Html for web
  universal_html: ^2.2.4
  ###### Background Remover End ######

  # For AI image generator from Url Internet
  #########################################################################"Ana Fasakht"
  #########################################################################""
  #########################################################################""
  #########################################################################""
  #image_downloader: ^0.31.0

  ### ToDo List
  # Jedidi add delete task slider
  flutter_slidable: ^3.0.1

  # Jedidi add text auto direction
  auto_direction: ^0.0.7

  ##### Parameter ######
  # Jedidi add an offline DataBase
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  #####GetX######
  # Save local values
  shared_preferences: ^2.2.2
  ###### GetX Begin ######
  get: ^4.6.6
  get_storage: ^2.1.1
  ###### GetX End ######
  velocity_x: ^4.1.2


  ###### Firebase Begin ######
  firebase_core: ^2.25.5
  # Authentification
  firebase_auth: ^4.17.6
  # Firestore
  cloud_firestore: ^4.13.6
  ###### Firebase End ######
  #connectivity_plus: ^5.0.2


  ###### Speech Begin ######
  # Text To Speech service
  flutter_tts: ^3.8.5
  # Speech To Text google
  speech_to_text: ^6.6.0
  ###### Speech End ######

  # Jedidi add dependencies

  # Floating button animation
  avatar_glow: ^3.0.1

  # copy text
  clipboard: ^0.1.3

  # share text & image
  share_plus: ^7.2.2



  ######################################
  # To use SVG in assets
  flutter_svg: ^1.0.0

  # Calendar
  table_calendar: ^3.0.9

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
#  flutter_native_splash: ^2.3.2
#  flutter_launcher_icons: ^0.13.1
#
## For information on the generic Dart part of this file, see the
## following page: https://dart.dev/tools/pub/pubspec
#flutter_native_splash:
#  color: "#88D008"
#  image: assets/sicon.png
#  android: true
#  android_12:
#    image: assets/sicon.png
#    icon_background_color: "#88D008"
#  ios: true
#  web: false
#flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon.png"
#  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
   - assets/
   - assets/images/
   - assets/images/SocialMedia/
   - assets/images/favicon.png
   - assets/logo/logo_home.png
   - assets/logo/logo_shape_light.png
   - assets/logo/logo_shape_light.png
   - assets/logo/
   - assets/svgs/
   - assets/health/
   - assets/medical/
   - assets/medical/icons/
   - assets/medical/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 300
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 700