// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnuCmmUrZFl_Zmav1IHfzgWTvKXPkCZHo',
    appId: '1:317598830665:web:519cddeb3a23d241dd2f98',
    messagingSenderId: '317598830665',
    projectId: 'smartdoai',
    authDomain: 'smartdoai.firebaseapp.com',
    storageBucket: 'smartdoai.appspot.com',
    measurementId: 'G-8KGPWCZJQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBueWKbuHi-xSXDP7D4Re5oIJDPTIWtCGA',
    appId: '1:317598830665:android:6ad622cd7a6ec91add2f98',
    messagingSenderId: '317598830665',
    projectId: 'smartdoai',
    storageBucket: 'smartdoai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaU8naTmdJUf5EeF3vbg1533KnpfX_6xU',
    appId: '1:317598830665:ios:ccbe83d9e60db08ddd2f98',
    messagingSenderId: '317598830665',
    projectId: 'smartdoai',
    storageBucket: 'smartdoai.appspot.com',
    iosBundleId: 'me.jedidi.tasknow.tasknow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaU8naTmdJUf5EeF3vbg1533KnpfX_6xU',
    appId: '1:317598830665:ios:89902bb1c66e5669dd2f98',
    messagingSenderId: '317598830665',
    projectId: 'smartdoai',
    storageBucket: 'smartdoai.appspot.com',
    iosBundleId: 'me.jedidi.tasknow.tasknow.RunnerTests',
  );
}
